import { describe, it, expect } from 'vitest';
import svg2ttf from '../src/index.ts';

const fixture = `<?xml version="1.0" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg">
<defs>
<font id="fontello" horiz-adv-x="1000" >
<font-face font-family="fontello" font-weight="400" font-stretch="normal" units-per-em="1000" ascent="850" descent="-150" />
<missing-glyph horiz-adv-x="1000" />
<glyph glyph-name="duckduckgo" unicode="&#xe807;" d="M0 349q0 215 141 355t355 141 356-141 140-355z" horiz-adv-x="992" />
</font>
</defs>
</svg>`;

describe('svg2ttf end-to-end', () => {
  it('should generate a ttf file and match expected base64 output', () => {
    // Use a fixed timestamp to ensure reproducible output
    const options = { ts: 1457357570 };
    const ttf = svg2ttf(fixture, options).buffer;
    const base64 = Buffer.from(ttf).toString('base64');

    const expectedBase64 =
      'AAEAAAALAIAAAwAwR1NVQiCLJXoAAAE4AAAAVE9TLzI+KkpWAAABjAAAAGBjbWFw6S+7vwAAAfQAAAFwZ2x5ZmZ+/rwAAANsAAAAJGhlYWQJDKs3AAAA4AAAADZoaGVhBz0DUwAAALwAAAAkaG10eAfIAAAAAAHsAAAACGxvY2EAEgAAAAADZAAAAAZtYXhwAQ0AEgAAARgAAAAgbmFtZZafyRQAAAOQAAACFnBvc3QxasfiAAAFqAAAADQAAQAAA1L/agAAA+gAAP/+A+gAAQAAAAAAAAAAAAAAAAAAAAIAAQAAAAEAAD8FZaVfDzz1AAsD6AAAAADTAzOCAAAAANMDM4IAAAAAA+gDTgAAAAgAAgAAAAAAAAABAAAAAgAGAAEAAAAAAAIAAAAKAAoAAAD/AAAAAAAAAAEAAAAKADAAPgACREZMVAAObGF0bgAaAAQAAAAAAAAAAQAAAAQAAAAAAAAAAQAAAAFsaWdhAAgAAAABAAAAAQAEAAQAAAABAAgAAQAGAAAAAQAAAAQD5AGQAAUAAAJ6ArwAAACMAnoCvAAAAeAAMQECAAACAAUDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFBmRWQAwOgH6AcDUv9qAFoDrACWAAAAAQAAAAAAAAAAAAAAAAACA+gAAAPgAAAAAAAFAAAAAwAAACwAAAAEAAABVAABAAAAAABOAAMAAQAAACwAAwAKAAABVAAEACIAAAAEAAQAAQAA6Af//wAA6Af//wAAAAEABAAAAAEAAAEGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAABwAAAAAAAAAAQAA6AcAAOgHAAAAAQAAAAAAEgAAAAEAAAAAA+IDTgAFAAARNAAkAAcBGgGsARwCAV3XARgC/uTVAAAAEADGAAEAAAAAAAEACAAAAAEAAAAAAAIABwAIAAEAAAAAAAMACAAPAAEAAAAAAAQACAAXAAEAAAAAAAUACwAfAAEAAAAAAAYACAAqAAEAAAAAAAoAKwAyAAEAAAAAAAsAEwBdAAMAAQQJAAEAEABwAAMAAQQJAAIADgCAAAMAAQQJAAMAEACOAAMAAQQJAAQAEACeAAMAAQQJAAUAFgCuAAMAAQQJAAYAEADEAAMAAQQJAAoAVgDUAAMAAQQJAAsAJgEqZm9udGVsbG9SZWd1bGFyZm9udGVsbG9mb250ZWxsb1ZlcnNpb24gMS4wZm9udGVsbG9HZW5lcmF0ZWQgYnkgc3ZnMnR0ZiBmcm9tIEZvbnRlbGxvIHByb2plY3QuaHR0cDovL2ZvbnRlbGxvLmNvbQBmAG8AbgB0AGUAbABsAG8AUgBlAGcAdQBsAGEAcgBmAG8AbgB0AGUAbABsAG8AZgBvAG4AdABlAGwAbABvAFYAZQByAHMAaQBvAG4AIAAxAC4AMABmAG8AbgB0AGUAbABsAG8ARwBlAG4AZQByAGEAdABlAGQAIABiAHkAIABzAHYAZwAyAHQAdABmACAAZgByAG8AbQAgAEYAbwBuAHQAZQBsAGwAbwAgAHAAcgBvAGoAZQBjAHQALgBoAHQAdABwADoALwAvAGYAbwBuAHQAZQBsAGwAbwAuAGMAbwBtAAAAAgAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAQIBAwAKZHVja2R1Y2tnbwAA';
    expect(base64).toBe(expectedBase64);
  });
});
